const ACCESS_TOKEN_LENGTH = '15m'

const REFRESH_TOKEN_LENGTH = '1d'
const REFRESH_TOKEN_MAX_AGE = 24 * 60 * 60 * 1000
const REFRESH_TOKEN_EXPIRED_AGE = 5 * 100
const REFRESH_TOKEN_JWT_COOKIE_NAME = 'jwt'


module.exports = {
    ACCESS_TOKEN_LENGTH ,
    REFRESH_TOKEN_LENGTH ,
    REFRESH_TOKEN_MAX_AGE ,
    REFRESH_TOKEN_EXPIRED_AGE,
    REFRESH_TOKEN_JWT_COOKIE_NAME
}

