// SOCKET.IO OPERATION CONSTANTS
const IO_POST_DELETE = "DELETE_POST"
const IO_POST_UPDATE = "UPDATE_POST"
const IO_POST_ADD = "ADD_POST"
const IO_REPLY_DELETE = "DELETE_REPLY"
const IO_REPLY_UPDATE = "UPDATE_REPLY"
const IO_REPLY_ADD = "ADD_REPLY"

module.exports = {
    IO_POST_DELETE,
    IO_POST_UPDATE,
    IO_POST_ADD,
    IO_REPLY_DELETE,
    IO_REPLY_UPDATE,
    IO_REPLY_ADD
}